rootProject.name = "spring-boot-examples"
include("spring-boot-mybatis-examples")
include("spring-boot-mybatis-examples:spring-boot-mybatis-postgre-example")
include("spring-boot-mysql-examples")
include("spring-boot-mysql-examples:spring-boot-mysql-common")
include("spring-boot-mysql-examples:spring-boot-mysql-config-code-example")
include("spring-boot-mysql-examples:spring-boot-mysql-config-yaml-example")
include("spring-boot-mysql-examples:spring-boot-mysql-test-init-sql-example")
include("spring-cloud-examples")
include("spring-cloud-examples:spring-cloud-zookeeper-example")
include("spring-cloud-huawei-examples")
include("spring-cloud-huawei-examples:spring-cloud-huawei-example")
include("spring-boot-apollo-example")
