openapi: 3.0.0
tags:
  - name: Validation
    description: Validation API
info:
  title: Validation API
  version: 1.0.0
paths:
  /validation:
    post:
      tags:
        - Validation
      summary: Try To Validation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidationReq'
      responses:
        '200':
          description: Validation Request
  /validation-parent-nullable-child-required:
    post:
      tags:
        - Validation
      summary: Try To Validation Parent Nullable Child Required
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                parent:
                  $ref: '#/components/schemas/RequiredChildNullableParentReq'
      responses:
        '200':
          description: Validation Parent Nullable Child Required
  /validation-path-string/{path}:
    get:
      tags:
        - Validation
      summary: Try To Validation Path String
      parameters:
        - name: path
          in: path
          required: true
          schema:
            type: string
            minLength: 1
            maxLength: 4
      responses:
        '200':
          description: Validation Path String
components:
  schemas:
    ValidationReq:
      type: object
      properties:
        validationInteger:
          type: integer
          minimum: 0
          maximum: 1024
        validationMap:
          $ref: '#/components/schemas/ValidationMap'
      required:
        - validationMap
    ValidationMap:
      type: object
      minProperties: 1
      maxProperties: 5
      additionalProperties:
        type: string
        minLength: 1
        maxLength: 32
    RequiredChildNullableParentReq:
      type: object
      properties:
        parent:
          $ref: '#/components/schemas/RequiredChildNullableParent'
    RequiredChildNullableParent:
      type: object
      properties:
        child:
          $ref: '#/components/schemas/RequiredChild'
      required:
        - child
    RequiredChild:
      type: object
      properties:
        validationString:
          type: string
          minLength: 1
          maxLength: 16
          pattern: '[a-z]{1,16}'
      required:
        - validationString
