server:
  port: 8888
spring:
  h2:
    console:
      enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
  sql:
    init:
      mode: embedded
      platform: h2
      schema-locations: classpath:schema.sql
